### ISSUE TITLE
Protobuf support only compiles with version 3.4.0

### ISSUE THREAD

**Issue by chrischen** [YuvalNirkin/find_face_landmarks#17]
Thought this should be noted as it states minimum version is 3.0.0, but it doesn't compile unless 3.4.0 is used.

**Comment by YuvalNirkin** [comment]
It should work with Protobuf 3.0.0 as well.
Compilation problems with Protobuf are very common because multiple  versions often exist on the same system.

**Comment by akashgoyal** [comment]
Hi @YuvalNirkin 
I am not able to compile this source code because of protobuf. I get a lot of errors like below
`undefined reference to `google::protobuf::Arena::AllocateAligned(std::type_info const*, unsigned long)'`

I have tried protobuf versions 2.6.1, 2.7.0, 3.0.x, 3.4.x but none of them seem to work
Any clue on what to fix ?

Thanks
Akash

**Comment by YuvalNirkin** [comment]
All Protobuf versions 3.0.x and above should work.
What you're getting is a linkage problem, make sure that you're linking with the right Protobuf libraries.
